### ISSUE TITLE
unable to read node_info.json

### ISSUE THREAD

**Issue by prabinsh** [DataStax-Toolkit/sperf#58]
When I run `core diag,` I run into the following command

```
parser warnings
---------------
* unable to read 'node_info.json'
```

I am running `cassandra 3.0.15` and I am manually running `collect_node_diag.sh` on each node. I have looked in the script but I can't seem to find where it is getting created. Is this DSE related?

**Comment by rsds143** [comment]
The node_info.json is generated by the opscenter diag tarball and can be used to find the read ahead for the cassandra drives. If the node_info.json is not present the read ahead is not guessed or attempted then.

Since that is only one diagnostic signal among many that is a safe to ignore warning in that case

**Comment by prabinsh** [comment]
Thank you for the explanation.
